# Generated by Django 3.2.13 on 2022-05-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=8192)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firesale.user')),
            ],
        ),
    ]
