# Generated by Django 3.2.13 on 2022-05-05 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0004_auto_20220505_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='user_image',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='firesale.image'),
        ),
    ]
