# Generated by Django 3.2.13 on 2022-05-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0005_alter_personalinformation_user_image'),
        ('firesale', '0005_condition_alter_item_condition'),
    ]

    operations = [
    ]
