# Generated by Django 3.2.13 on 2022-05-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0006_merge_20220506_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=8192),
        ),
    ]
