# Generated by Django 3.2.13 on 2022-05-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0007_alter_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_date', models.DateField()),
                ('cvc', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=16384),
        ),
    ]
