# Generated by Django 3.2.13 on 2022-05-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0010_auto_20220512_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
