# Generated by Django 3.2.13 on 2022-05-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0011_item_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='country',
            field=models.CharField(blank=True, default='ISL', max_length=255),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='house_number',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='postal_code',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='street_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
