# Generated by Django 3.2.13 on 2022-05-13 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0012_auto_20220513_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='payment_info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='firesale.payment'),
        ),
    ]
