# Generated by Django 3.2.13 on 2022-05-13 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0013_personalinformation_payment_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='rating',
            field=models.FloatField(default=None, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
